charts_highcharts:
  version: VERSION
  js:
    js/charts_highcharts.js: {}
  dependencies:
      - core/jquery
      - core/jquery.once
      - core/drupal

highcharts:
  remote: https://code.highcharts.com/highcharts.js
  version: VERSION
  license:
      name: Non-commercial
      url: https://creativecommons.org/licenses/by-nc/3.0/
      gpl-compatible: false
  js:
    vendor/highcharts/highcharts.js: {}
  dependencies:
      - charts_highcharts/charts_highcharts
