<?php

/**
 * @file
 * Examples demonstrating how to implement and invoke hooks.
 */

/**
 * Implements hook_cron().
 *
 * We implement hook_cron() to do "background" processing. It gets called every
 * time the Drupal cron runs. We then decide what has to happen in response.
 *
 * Delete the image made while procesing 
 */
function dm_simple_cron() {
	//todo: check the day
	if(count(scandir('sites/default/files/tensorflow'))>50){
		exec("rm sites/default/files/tensorflow/page-*.jpg");
		exec('rm sites/default/files/tensorflow/table-*.jpg');
	}
}